name: List files
run: ls -R



on:
  workflow_dispatch:  # permette di avviare manualmente dallo smartphone o dal web

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # evita warning Node.js 20

    steps:
      # 1️⃣ Recupera i file della repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Installa Python 3.11
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Installa le librerie richieste
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r python_script/requirements.txt
